### PR TITLE
Add last-updated as an option for secondary_info type

### LINKED ISSUE #59: Feature request: last-updated in addition to last-changed
It would be nice to see if there is communication with the AC/Thermostats. With last-updated I would see if there is data exchange all the time. The best would it be to even get that in the bottom line, like this:

image

I had problem with some thermostats and did not saw it, so my house was a bit colder today. No big issue, but maybe I would see that when there would be indication for communication fault/lost. Even last changed would not really help, but last update should help, because normally there is refresh every 60s.

Thank you in advance!

```
type: custom:mini-climate
entity: climate.mp_smartthermostat_112_1
target_temperature:
  step: 0.5
temperature:
  round: 0
indicators:
  temperature:
    icon: mdi:thermometer
    unit: °C
    round: 2
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_10
  humidity:
    icon: mdi:water
    unit: '%'
    round: 1
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_11
  pressure:
    icon: mdi:gauge
    unit: hPa
    round: 1
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_12
```

### LINKED ISSUE #63: Feature request: last-updated in addition to last-changed
I would like to see the following option available:

```
- type: custom:mini-climate
  entity: climate.nest
  name: Nest thermostaat
  icon: mdi:fire           
  secondary_info:
    type: last-updated
```

Schermafbeelding 2022-01-15 om 17 54 06

With `last-changed` (Laatst gewijzigd: 1 uur geleden) it shows the last time the temperature changed. 
I would want it to show the last time the entity was updates (Laatst bijgewerkt: 8 minuten geleden)

Thanks in advance.

### PR DESCRIPTION
**Pull request by parrel**
Did not yet add it to the Readme.
Fixes #59 
Fixes #63

### CODE REVIEW

**Comment by regevbr** [comment]
@parrel please rebase

**Comment by parrel** [comment]
@regevbr Done

**Comment by regevbr** [comment]
Thanks, i will merge once you update the readme

**Comment by parrel** [comment]
The reason because I didn't add the new option to the docs is because I don't know how you want to add it.

https://github.com/artem-sedykh/mini-climate-card/blob/f45e9567d638201856704924defb94ff3ac5a881/README.md?plain=1#L82

Do you want me to add it to this list and change the version to v2.2.0?

**Comment by regevbr** [comment]
@parrel do you want to complete this PR?

**Comment by parrel** [comment]
Hi, I'm short in time at the moment. You can do it if you want. Otherwise it will be this weekend.

**Comment by regevbr** [comment]
No rush just wanted to make sure this will not become stale

**Comment by parrel** [comment]
@regevbr Added it to the docs ;)

**Comment by regevbr** [comment]
thanks @parrel released in https://github.com/artem-sedykh/mini-climate-card/releases/tag/v2.1.1

**Pull request merged**
