### PR TITLE
fix #66: 2022.3.X Breaks dropdown

### LINKED ISSUE #66: 2022.3.X Breaks dropdown
You are using paper-menu-button and paper-listbox with the assumption Home Assistant will load these elements.

In 2022.3 these elements are no longer part of Home Assistant, so this will no longer work.

see https://github.com/kalkih/mini-media-player/issues/606 for reference

image

edit:
[hotfix](https://gist.github.com/regevbr/5adc681805e88bf7092381137225f3eb) exists

### PR DESCRIPTION
**Pull request by regevbr**
fix #66 

So according to https://developers.home-assistant.io/blog/2022/02/18/paper-elements/ all paper elements are not supported anymore starting 2022.3 and they recommend using mwc components instead. The current behavior is a complete breakdown of the dropdown menus.
After a couple of hours, I managed to get it working, but sadly CSS and positioning stuff is where I'm no longer effective. @artem-sedykh if you can take it from here and sort out the styling it will be awesome :-)

### CODE REVIEW

**Comment by regevbr** [comment]
@artem-sedykh I also fixed the positioning, I believe this PR is ready to be merged and would appreciate your CR. Need to note that this is probably will not work on previous versions of HA and as such, I added a comment in the readme and updated the version to 2 (as this is a breaking change).

https://user-images.githubusercontent.com/5775519/155855489-6f7ff7e7-4443-40d0-a960-197858bff67d.mp4

**Comment by regevbr** [comment]
I'm actually having trouble in mobile view when this card is way down in the scrolled view- the fixed positioning of the drop downs doesn't take under consideration the scroll position...

**Comment by regevbr** [comment]
> I'm actually having trouble in mobile view when this card is way down in the scrolled view- the fixed positioning of the drop downs doesn't take under consideration the scroll position...

It seems that those issues are resolved in the newest beta version (maybe they were related to the HA frontend)
@artem-sedykh can you please CR?

**Comment by regevbr** [comment]
To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/5adc681805e88bf7092381137225f3eb)

**Comment by Mithrox** [comment]
Is there a timeframe as to when the beta version is released? I still have the issues with the dropdown before being, and therefore the card being much higher than it used to be, and unfortunately I did not get the fix posted above to work. So I dont mind waiting for the release, but as far as I can see there has been no release yet?

**Comment by acdcnow** [comment]
@regevbr looks like that he is not working any more on that repo... guess he has other issues ... look where he is from.. Moscow RU
could you create a release in your fork?

**Pull request merged**
